project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Caffiene Consumption and Depression"
  author:
    - Shiyun Chen (sc5324)
    - Anqi Wang (aw3615)
  repo-url: https://github.com/shiyuc4-1833404/depresslevel
  date: today
  page-footer:
    right: |
      This book was built with <a href=" ">Quarto</a >.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true
